services:
  iban-validator:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - uvicorn 
      - "app.main:app" 
      - --host 
      - "0.0.0.0"
      - --port
      - "80"
    ports:
      - 80:80