services:
  app:
    build:
      context: .
      target: app
      dockerfile: Dockerfile
    ports:
      - 8080:80
  test:
    build:
      context: .
      target: test
      dockerfile: Dockerfile